[book]
authors = ["youbetdao"]
language = "zh"
multilingual = true
src = "src"
title = "youbet-tutorial"

[output.html]
additional-css = ["custom.css"]
additional-js = ["custom.js"]
git-repository-url = "https://github.com/youbetdao/epf-protocol-cn/"
git-repository-icon = "fa-github"

[preprocessor.katex]
after = ["links"]
